/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dunk/dunk.gltf --transform 
Files: dunk/dunk.gltf [24.63KB] > C:\Users\franc\Desktop\Works\ReactAppTest\reactapp2\dunk-transformed.glb [3.81MB] (-15353%)
Author: ryanbair (https://sketchfab.com/ryanbair)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yellow-nike-dunk-low-dusty-olive-from-video-clip-93be9098ab9c46329cbeae98f458a912
Title: Yellow Nike Dunk Low Dusty Olive from video clip
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/dunk-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.tex_u1_v1}
        scale={0.05}
      />
    </group>
  );
}

useGLTF.preload('/dunk-transformed.glb');
