/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dunkhigh/dunkhigh.gltf --transform 
Files: dunkhigh/dunkhigh.gltf [54.12KB] > C:\Users\franc\Desktop\Works\ReactAppTest\reactapp2\dunkhigh-transformed.glb [8.21MB] (-15077%)
Author: ryanbair (https://sketchfab.com/ryanbair)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-dunk-high-hawaii-b91992960af540c7a1edef97bf4d7ef1
Title: Nike Dunk High Hawaii
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function ModelHigh(props) {
  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/dunkhigh-transformed.glb`
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.tex_u1_v1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload(`${process.env.PUBLIC_URL}/dunkhigh-transformed.glb`);
