/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pool_ball/scene.gltf --transform 
Files: pool_ball/scene.gltf [4.61KB] > C:\Users\franc\Desktop\Works\ReactAppTest\reactapp2\scene-transformed.glb [402.73KB] (-8636%)
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pool-ball-405f6ed74fa94dbd9a06629a334585db
Title: Pool Ball
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function PoolBall(props) {
  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/scene-transformed.glb`
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.None}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(`${process.env.PUBLIC_URL}/scene-transformed.glb`);
